name : first workflow
on : workflow_dispatch
jobs :
  first-job:
    runs-on: ubuntu_latest
    steps:
     - name: print greeting
       run : echo "Hello world !!"
     - name : print goodbye
       run : echo "good bye"
    
