name: jqDeploy Orchestrator

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution unique name (not display name).'
        required: true

env:  # <<=== Define all non-secret envs here!
  DEV_ENV_URL: 'https://org23b23f97.crm.dynamics.com'
  TEST_ENV_URL: 'https://orgd93932c9.crm.dynamics.com'
  EXPORT_FOLDER: ./exported
  MANAGED_FOLDER: ./exported/managed
  UNMANAGED_FOLDER: ./exported/unmanaged
  UNPACKED_FOLDER: ./exported/unpacked

jobs:
  export:
    uses: demo/.github/workflows/w1-export.yml@main
    with:
      solution_name: ${{ github.event.inputs.solution_name }}
      dev_env_url: ${{ env.DEV_ENV_URL }}
      export_folder: ${{ env.EXPORT_FOLDER }}
      managed_folder: ${{ env.MANAGED_FOLDER }}
      unmanaged_folder: ${{ env.UNMANAGED_FOLDER }}
      unpacked_folder: ${{ env.UNPACKED_FOLDER }}
      azure_tenant_id: ${{ secrets.PP_TENANT_ID }}
      azure_client_id: ${{ secrets.PP_CLIENT_ID }}
      azure_client_secret: ${{ secrets.PP_CLIENT_SECRET }}
    secrets: inherit

  patch:
    needs: export
    uses: demo/.github/workflows/w2-patch.yml@main
    with:
      solution_name: ${{ github.event.inputs.solution_name }}
      managed_folder: ${{ env.MANAGED_FOLDER }}
      unpacked_folder: ${{ env.UNPACKED_FOLDER }}
      test_env_url: ${{ env.TEST_ENV_URL }}
      azure_tenant_id: ${{ secrets.PP_TENANT_ID }}
      azure_client_id: ${{ secrets.PP_CLIENT_ID }}
      azure_client_secret: ${{ secrets.PP_CLIENT_SECRET }}
    secrets: inherit

  import:
    needs: [export, patch]
    uses: demo/.github/workflows/w3-import.yml@main
    with:
      solution_name: ${{ github.event.inputs.solution_name }}
      managed_folder: ${{ env.MANAGED_FOLDER }}
      test_env_url: ${{ env.TEST_ENV_URL }}
      azure_tenant_id: ${{ secrets.PP_TENANT_ID }}
      azure_client_id: ${{ secrets.PP_CLIENT_ID }}
      azure_client_secret: ${{ secrets.PP_CLIENT_SECRET }}
    secrets: inherit

